const fs = require('fs');
const path = require('path');

// Configuration
const CONFIG = {
  patients: 10000,
  staff: 100,
  encounters: 50000,
  invoices: 40000,
  outputFile: path.join(__dirname, 'seed_large_data.sql')
};

// Helpers
const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const randomChoice = (arr) => arr[Math.floor(Math.random() * arr.length)];
const randomPhone = () => `13${randomInt(0, 9)}${randomInt(10000000, 99999999)}`;
const randomDate = (start, end) => new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime())).toISOString().slice(0, 10);

const stream = fs.createWriteStream(CONFIG.outputFile);

function write(str) {
  stream.write(str + '\n');
}

console.log(`Generating data script to ${CONFIG.outputFile}...`);

write('-- Performance Test Data Seed Script');
write('-- Generated by generate_data.js');
write('SET FOREIGN_KEY_CHECKS=0;');
write('SET UNIQUE_CHECKS=0;');
write('SET AUTOCOMMIT=0;');

// 1. Generate Patients
console.log('Generating Patients...');
write('INSERT INTO patient (patient_name, gender, birth_date, id_card_no, phone, address, created_at) VALUES');
const patients = [];
for (let i = 0; i < CONFIG.patients; i++) {
  const gender = randomChoice(['M', 'F']);
  const birth = randomDate(new Date('1950-01-01'), new Date('2020-01-01'));
  const idCard = `ID_${i}_${randomInt(1000, 9999)}`;
  const values = `('Patient_${i}', '${gender}', '${birth}', '${idCard}', '${randomPhone()}', 'Address ${i}', NOW())`;
  patients.push(values);
  if (patients.length >= 1000) {
    write(patients.join(',') + ';');
    write('INSERT INTO patient (patient_name, gender, birth_date, id_card_no, phone, address, created_at) VALUES');
    patients.length = 0;
  }
}
if (patients.length > 0) write(patients.join(',') + ';');

// 2. Generate Encounters (Assuming doctors exist with IDs 1-20)
console.log('Generating Encounters...');
write('INSERT INTO encounter (patient_id, department_id, doctor_id, encounter_type, status, created_at) VALUES');
const encounters = [];
for (let i = 0; i < CONFIG.encounters; i++) {
  const pid = randomInt(1, CONFIG.patients);
  const dept = randomInt(1, 5);
  const doc = randomInt(1, 20); // Assuming 20 doctors
  const type = randomChoice(['OUTPATIENT', 'EMERGENCY']);
  const status = 'COMPLETED';
  const values = `(${pid}, ${dept}, ${doc}, '${type}', '${status}', NOW())`;
  encounters.push(values);
  if (encounters.length >= 1000) {
    write(encounters.join(',') + ';');
    write('INSERT INTO encounter (patient_id, department_id, doctor_id, encounter_type, status, created_at) VALUES');
    encounters.length = 0;
  }
}
if (encounters.length > 0) write(encounters.join(',') + ';');

write('COMMIT;');
write('SET FOREIGN_KEY_CHECKS=1;');
write('SET UNIQUE_CHECKS=1;');
write('SET AUTOCOMMIT=1;');

stream.end(() => {
  console.log('Done! SQL script generated.');
});
